# Generated by Django 5.1.3 on 2024-12-14 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_author_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='registration_number',
        ),
    ]
