# Generated by Django 5.1.3 on 2024-12-16 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_comment_user_email_remove_comment_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='registration_number',
            field=models.CharField(default='SP22-BSE-020', max_length=40, unique=True),
            preserve_default=False,
        ),
    ]
