# Generated by Django 5.1.3 on 2024-12-16 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_comment_user_comment_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='registration_number',
            field=models.CharField(max_length=40, null=True, unique=True),
        ),
    ]
